namespace FudgeUserInterface {

  export type DROPEFFECT = "none" | "copy" | "link" | "move";

  export const enum EVENT {
    CLICK = "click",
    DOUBLE_CLICK = "dblclick",
    KEY_DOWN = "keydown",
    KEY_UP = "keyup",
    DRAG_START = "dragstart",
    DRAG = "drag",
    DRAG_END = "dragend",
    DRAG_ENTER = "dragenter",
    DRAG_OVER = "dragover",
    DRAG_LEAVE = "dragleave",
    DROP = "drop",
    POINTER_UP = "pointerup",
    WHEEL = "wheel",
    FOCUS_NEXT = "focusNext",
    FOCUS_PREVIOUS = "focusPrevious",
    FOCUS_IN = "focusin",
    FOCUS_OUT = "focusout",
    FOCUS_SET = "focusSet",
    FOCUS = "focus",
    BLUR = "blur",
    CHANGE = "change",
    DELETE = "delete",
    RENAME = "rename",
    SELECT = "itemselect",
    ESCAPE = "escape",
    COPY = "copy",
    CUT = "cut",
    PASTE = "paste",
    SORT = "sort",
    CONTEXTMENU = "contextmenu",
    MUTATE = "mutate",
    REMOVE_CHILD = "removeChild",
    COLLAPSE = "collapse",
    EXPAND = "expand",
    INPUT = "input",
    REARRANGE_ARRAY = "rearrangeArray",
    TOGGLE = "toggle",
    POINTER_MOVE = "pointermove",
    SELECT_ALL = "selectAll",
    SAVE_HISTORY = "saveHistory",
    REFRESH_OPTIONS = "refreshOptions",
    SET_VALUE = "setValue",
    CREATE_VALUE = "initializeValue"
  }
}